config/routes.rb
Rails.application.routes.draw do
  resources :projects

  get 'index' => 'index#index'

  get 'index/fav_list'

  get 'admin' => 'admin#index'

  get 'admin/index'

  get 'admin/projects' => 'admin#list', as: 'admin_list'

  get 'admin/projects/:id' => 'admin#detail', as: 'detail_admin'

  get 'admin/entries'

  get 'admin/reqest'

  get 'admin/entries/:id' => 'admin#approval', as: 'approval'

  get 'admin/projects/:id/edit' => 'admin#edit', as: 'edit'

  get 'admin/word_list' => 'admin#word_list'

  get 'fav' => 'projects#fav'

  get '/' => 'index#index'

  get 'setup' => 'projects#setup'

  post 'fav_remove' => 'projects#fav_remove'

  post 'fav_remove' => 'index#fav_remove'

  post 'fav' => 'projects#fav'

  post 'confirm' => 'admin#confirm'

  post 'reject' => 'admin#reject'

  post 'destroy' => 'admin#destroy'

  post 'make' => 'admin#make'

  post 'kind' => 'projects#kind'

end

app/views/admin/_form.html.erb
<%= form_for @project do |f| %>
<div class="form-group">
  <div class="input-group">
    <%= f.label '名前' %>
    <%= f.text_field :name, :placeholder => 'KeTchUp', :class => "form-control" %>
  </div>
  <div class="input-group">
    <%= f.label 'フリガナ' %>
    <%= f.text_field :kana, :placeholder => 'ケチャップ', :class => "form-control" %>
  </div>
  <div class="input-group">
    <%= f.label '概要' %>
    <%= f.text_field :about, :placeholder => 'おむらいすが製作した筑波大学用語辞典', :class => "form-control" %>
  </div>
  <div class="input-group">
    <%= f.label '詳細' %>
    <%= f.text_area :detail, :class => "form-control" %>
  </div>
  <div class="input-group">
    <%= f.label '大カテゴリー' %>
    <%= f.select :kind1, options_for_select(@kind1s.collect { |country| [country.kind1.titleize, country.id] }, 1), {}, { id: 'kind1s_select', :class => "form-control"} %>
  </div>
  <div class="input-group">
    <%= f.label '小カテゴリー' %>
    <%= f.text_field :kind2, :placeholder => 'イタリアン サークル等', :class => "form-control" %>
  </div>
  <div class="input-group">
    <%= f.label '同義語、類義語' %>
    <%= f.text_field :synonym, :placeholder => '辞書 辞典 事典 Webアプリケージョン', :class => "form-control" %>
  </div>
  <div class="input-group input_sub">
    <%= f.submit '更新', data: {:disable_with => '更新中', confirm: '内容を更新します'}, :class => 'btn btn-primary' %>
  </div>
</div>
<% end %>
<%= stylesheet_link_tag "form", :media => "all" %>

app/views/admin/approval.html.erb
<h1><%= @entry.name %></h1>
<h2><%= @entry.about %></h2>
<p><%= simple_format(@entry.detail.gsub(/\\n/, "\n")) %></p>
<p><%= @entry.kind1 %></p>
<p><%= @entry.kind2 %></p>
<p><%= @entry.kana %></p>
<p><%= @entry.synonym %></p>
<%= button_to "承認", {:action => "confirm", :data => {:id => @entry.id, :name => @entry.name, :kana => @entry.kana, :about => @entry.about, :detail => @entry.detail, :kind1 => @entry.kind1, :kind2 => @entry.kind2, :synonym => @entry.synonym}}, :remote => false, data: {:confirm => "登録を承認します。"}, :class => "btn btn-success" %>
<ul class="inline-block">
  <li>
    <%= link_to '編集', edit_path, :class => "btn btn-warning" %>
  </li>
  <li>
    <%= button_to "非承認", {:action => "reject", :data => @entry.id}, :remote => false, data: {:disable_with => '拒否中', confirm: "登録を拒否します。"}, :class => "btn btn-danger" %>
  </li>
  <li>
    <%= link_to 'トップ', admin_index_path, :class => "btn btn-primary" %>
  </li>
</ul>
<%= stylesheet_link_tag "detail", :media=> "all" %>

app/views/admin/detail.html.erb
<header>
  <div class="title">
  <p>筑波大学用語辞典</p>
</div>
</header>
<%= link_to admin_index_path, :class => 'top' do %>
  <%= image_tag 'image.png' , :width => '250', :height => '100'%>
<% end %>
<div class="info_detail">
<h1>ワード名：<%= @project.name %></h1>
<h2>概要：<%= @project.about %></h2>
<p>詳細：<%= simple_format(@project.detail.gsub(/\\n/, "\n")) %></p>
<p>大カテゴリー：<%= @project.kind1 %></p>
<p>小カテゴリー<%= @project.kind2 %></p>
<p>カナ<%= @project.kana %></p>
<p>同義語、類義語<%= @project.synonym %></p>
</div>
<ul class="inline-block">
	<li>
    <%= link_to '編集', edit_path, :class => "btn btn-warning" %>
  </li>
	<li>
    <%= button_to "削除", {:action => "destroy", :data => @project.id}, :remote => false, data: {confirm: "削除します。"}, :class => "btn btn-danger" %>
  </li>
	<li>
    <%= link_to '一覧', admin_list_path, :class => "btn btn-primary" %>
  </li>
  <li>
    <%= link_to 'トップ', admin_index_path, :class => "btn btn-success" %>
  </li>
</ul>
<%= stylesheet_link_tag "detail", :media=> "all" %>

app/views/admin/edit.html.erb
<header>
  <div class="title">
  <p>筑波大学用語辞典</p>
</div>
</header>
<%= link_to admin_index_path, :class => 'top' do %>
  <%= image_tag 'image.png' , :width => '250', :height => '100'%>
<% end %>
<%= render 'form' %>

app/views/admin/entries.html.erb
<header>
  <div class="title">
  <p>筑波大学用語辞典</p>
</div>
</header>
<%= link_to admin_index_path, :class => 'top' do %>
  <%= image_tag 'image.png' , :width => '250', :height => '100'%>
<% end %>
<h1>申請一覧</h1>
<table id="list_fav" class="table table-striped">
  <tr>
    <th>用語名</th>
    <th>概要</th>
    <th>大カテゴリー</th>
    <th>小カテゴリー</th>
  </tr>
  <% @entry.each do |project| %>
  <tr>
    <td><%= link_to project.name, approval_path(project.id) %></td>
    <td><%= link_to project.about, approval_path(project.id) %></td>
    <td><%= link_to project.kind1, approval_path(project.id) %></td>
    <td><%= link_to project.kind2, approval_path(project.id) %></td>
  </tr>
  <% end %>
</table>
<ul class="inline-block">
  <li>
    <%= button_to '更新', {:action => 'make'}, data: {:disable_with => '更新中', confirm: "TFIDFの更新を行います。この作業には3分ほどかかります。"}, :class => "btn btn-danger" %>
  </li>
  <li>
    <%= link_to 'トップ', admin_index_path, :class => "btn btn-success" %>
  </li>
</ul>
<%= stylesheet_link_tag "detail", :media=> "all" %>

app/views/admin/index.html.erb
<header>
  <div class="title">
  <p>筑波大学用語辞典</p>
</div>
</header>
<%= link_to admin_index_path, :class => 'top' do %>
  <%= image_tag 'image.png' , :width => '250', :height => '100'%>
<% end %>
<table class="table table-striped">
  <tr>
    <td><%= link_to '一覧', admin_list_path %></td>
  </tr>
  <tr>
    <td><%= link_to '申請', admin_entries_path %></td>
  </tr>
</table>

app/views/admin/list.html.erb
<header>
  <div class="title">
  <p>筑波大学用語辞典</p>
</div>
</header>
<%= link_to admin_index_path, :class => 'top' do %>
  <%= image_tag 'image.png' , :width => '250', :height => '100'%>
<% end %>
<h1>一覧</h1>
<table class="table table-striped">
  <tr>
    <th>用語名</th>
    <th>概要</th>
    <th>大カテゴリー</th>
    <th>小カテゴリー</th>
  </tr>
  <% @projects.each do |project| %>
  <tr>
    <td><%= link_to project.name, detail_admin_path(project.id) %></td>
    <td><%= link_to project.about, detail_admin_path(project.id) %></td>
    <td><%= link_to project.kind1, detail_admin_path(project.id) %></td>
    <td><%= link_to project.kind2, detail_admin_path(project.id) %></td>
  </tr>
  <% end %>
</table>
<%= link_to 'トップ', admin_index_path %>
<%= stylesheet_link_tag "list", :media=> "all" %>

app/views/admin/reqest.html.erb
<h1>Admin#reqest</h1>
<p>Find me in app/views/admin/reqest.html.erb</p>

app/views/admin/word_list.html.erb
<header>
  <div class="title">
  <p>筑波大学用語辞典</p>
</div>
</header>
<%= link_to admin_index_path, :class => 'top' do %>
  <%= image_tag 'image.png' , :width => '250', :height => '100'%>
<% end %>
<table id="list_fav" class="table table-striped">
  <tr>
    <th>ID</th>
    <th>用語ID</th>
    <th>ワード</th>
    <th>TfIdf</th>
  </tr>
  <% @searches.each do |s| %>
  <tr>
    <td><%= s.id %></td>
    <td><%= s.project_id %></td>
    <td><%= s.word %></td>
    <td><%= s.tfidf %></td>
  </tr>
  <% end %>
</table>
<%= link_to 'トップ', admin_index_path %>