config/routes.rb
Rails.application.routes.draw do
  resources :projects

  get 'index' => 'index#index'

  get 'index/fav_list'

  get 'admin' => 'admin#index'

  get 'admin/index'

  get 'admin/projects' => 'admin#list', as: 'admin_list'

  get 'admin/projects/:id' => 'admin#detail', as: 'detail_admin'

  get 'admin/entries'

  get 'admin/reqest'

  get 'admin/entries/:id' => 'admin#approval', as: 'approval'

  get 'admin/projects/:id/edit' => 'admin#edit', as: 'edit'

  get 'admin/word_list' => 'admin#word_list'

  get 'fav' => 'projects#fav'

  get '/' => 'index#index'

  get 'setup' => 'projects#setup'

  post 'fav_remove' => 'projects#fav_remove'

  post 'fav_remove' => 'index#fav_remove'

  post 'fav' => 'projects#fav'

  post 'confirm' => 'admin#confirm'

  post 'reject' => 'admin#reject'

  post 'destroy' => 'admin#destroy'

  post 'make' => 'admin#make'

  post 'kind' => 'projects#kind'

end

app/views/index/_project.html.erb
<div id="word" class="fadein">
  <%= link_to project_path(@project.id) do %>
    <%= @project.name %>
  <% end %>
</div>

app/views/index/fav_list.html.erb
<header>
  <div class="title">
  <p>筑波大学用語辞典</p>
</div>
</header>
<%= link_to index_path, :class => 'top' do %>
  <%= image_tag 'image.png' , :width => '250', :height => '100'%>
<% end %>
<h1>お気に入り</h1>

<table id="fav_list" class="table table-striped">
  <tr>
    <th>お気に入り一覧</th>
    <th></th>
  </tr>
  <% @lists.each do |key, val| %>
  <tr>
    <td class="fav_all">
      <%= link_to project_path(key) do %>
        <%= val %>
      <% end %>
    </td>
    <td class="btn_right">
      <%= button_to "お気に入り解除", {:action => "fav_remove", :data => {:id => key}}, :remote => true, :onclick => "disable()", :class => "btn btn-danger fav-btn favorite_action" %>
    </td>
  </tr>
  <% end %>
</table>
<%= link_to 'トップ', index_path, :class => "btn btn-success" %>
<%= stylesheet_link_tag "list", :media => "all" %>
<%= javascript_include_tag "disable" %>

app/views/index/fav_list.js.erb
$('#fav_list').html('<%= j(render("fav")) %>');

app/views/index/index.html.erb
<%= favicon_link_tag('favicon.ico') %>

<header>
  <div class="title">
  <p>筑波大学用語辞典</p>
  <h1><%= link_to index_path, :class => "top" do %>
        <%= image_tag 'favicon.ico' %>&nbsp;KeTchUp
      <% end %></h1>
  <h2>明日のために調べよう!</h2>
</div>
</header>
<div id="word_area" class="center">
  <div id="word" class="fadein">
    <%= link_to project_path(@project.id) do %>
      <%= @project.name %>
    <% end %>
  </div>
</div>
<%= search_form_for @q do |f| %>
<div class="form-group">
  <div class="input-group">
    <%= f.text_field :name, :class => "form-control" %>
    <span class="input-group-btn">
      <%= button_tag( class: "btn btn-primary btn-lg", value: "search") do %>
        <%= content_tag :span, "検索", class: "glyphicon glyphicon-search" %>
      <% end %>
    </span>
  </div>
</div>
<% end %>

<div class="center fav-new">
  <%= link_to "お気に入り一覧", index_fav_list_path, :class => "btn btn-warning" %>
  <%= link_to '新規登録', new_project_path, :class => "btn btn-info" %>
</div>


<script>
function new_project() {
  $.ajax({
    url: 'index',
    type: 'GET',
    dataType: 'script'
    });
  setTimeout(execute,8500);
  }

  setInterval(new_project, 10000);
</script>
<%= stylesheet_link_tag "index", :media => "all" %>
<%= javascript_include_tag "fade" %>

app/views/index/index.js.erb
$('#word_area').html('<%= j(render("project")) %>');