config/routes.rb
Rails.application.routes.draw do
  resources :projects

  get 'index' => 'index#index'

  get 'index/fav_list'

  get 'admin' => 'admin#index'

  get 'admin/index'

  get 'admin/projects' => 'admin#list', as: 'admin_list'

  get 'admin/projects/:id' => 'admin#detail', as: 'detail_admin'

  get 'admin/entries'

  get 'admin/reqest'

  get 'admin/entries/:id' => 'admin#approval', as: 'approval'

  get 'admin/projects/:id/edit' => 'admin#edit', as: 'edit'

  get 'admin/word_list' => 'admin#word_list'

  get 'fav' => 'projects#fav'

  get '/' => 'index#index'

  get 'setup' => 'projects#setup'

  post 'fav_remove' => 'projects#fav_remove'

  post 'fav_remove' => 'index#fav_remove'

  post 'fav' => 'projects#fav'

  post 'confirm' => 'admin#confirm'

  post 'reject' => 'admin#reject'

  post 'destroy' => 'admin#destroy'

  post 'make' => 'admin#make'

  post 'kind' => 'projects#kind'

end

app/models/project.rb
class Project < ActiveRecord::Base
  has_many :searches, dependent: :destroy
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  def index
    if params[:kind] != nil
      if session[:back] == nil
        @value = params[:kind]
        if params.include?(:q)
          @q = Project.search(:kind1_or_kind2_eq => params[:kind], :s => params[:q][:s])
        else
          @q = Project.search(:kind1_or_kind2_eq => params[:kind])
        end
          @projects = @q.result.page(params[:page])
      else
        @s = session[:back]
        if params.include?(:q)
          @q = Project.search(:id_eq_any => @s, :s => params[:q][:s])
        else
          @q = Project.search(:id_eq_any => @s)
        end
        @projects = Project.page(params[:page]).where(id: @s).where(id: @s).order("field(id, #{@s.join(',')})")
      end
    else
      if session[:back] == nil
        if params.include?(:q)
          if params[:q].include?(:name)
            if params[:q][:name] == ""
              @q = Project.search(params[:q])
              @projects = @q.result.page(params[:page])
            else
              conversion
              search
              @q = Project.search(:id_eq_any => @sort, :s => params[:q][:s])
              if @sort.empty?
                @q = Project.search(:id_eq => 0)
                @projects = @q.result.page(params[:page])
              else
                if @q.sorts.empty?
                  @projects = Project.page(params[:page]).where(id: @sort).where(id: @sort).order("field(id, #{@sort.join(',')})")
                else
                  @projects = @q.result.page(params[:page])
                end
              end
            end
          else
            @q = Project.search(params[:q])
            @projects = @q.result.page(params[:page])
          end
        else
          @q = Project.search(params[:q])
          @projects = @q.result.page(params[:page])
        end
      else
        @s = session[:back]
        @q = Project.search(:id_eq_any => @s, :s => params[:q][:s])
        @projects = Project.where(id: @s).where(id: @s).order("field(id, #{@s.join(',')})")
      end
    end
    session[:back] = nil
    fav_list
    if cookies[:kind] == nil
      @project = Project.all.sample
    elsif cookies[:kind] == ""
      @project = Project.all.sample
    else
      @project = Project.where(kind1: cookies[:kind].split(/&/)).sample
    end
  end

  def show
    @project = Project.find(params[:id])
    detail
    search
    fav_list
    @sort.delete(params[:id].to_i)
    if @sort.empty?
      @q = Project.search(:id_eq => 0)
      @projects = @q.result
    else
      @sort = @sort.take(5)
      @projects = Project.where(id: @sort).where(id: @sort).order("field(id, #{@sort.join(',')})")
    end
  end

  def refine
    @q = Project.search(:kind1_or_kind2_eq => params[:data])
    @projects = @q.result.page(params[:page])
    fav_list
  end

  def fav
    @project = Project.find(params[:data][:id])
    if cookies[:fav] == nil
      key = Hash.new
    else
      key = JSON.parse(cookies[:fav])
    end
    key[@project.id] = @project.name
    cookies.permanent[:fav] = {:value => key.to_json}
    count = @project.count
    Project.update(@project.id, :count => count + 1)
    respond_to do |format|
      format.js {render inline: "location.reload();" }
    end
  end

  def fav_remove
    @project = Project.find(params[:data][:id])
    count = @project.count
    Project.update(@project.id, :count => count - 1)
    key = JSON.parse(cookies[:fav])
    key.delete(params[:data][:id])
    cookies.permanent[:fav] = {:value => key.to_json}
    respond_to do |format|
      format.js {render inline: "location.reload();" }
    end
  end

  def fav_list
    if cookies[:fav] == nil
      @lists = Hash.new
    else
      @lists = JSON.parse(cookies[:fav])
    end
  end

  def new
    @project = Entry.new
    @kind1s = Kind1.all
  end

  def kind2_select
    @kind2s = Kind2.where(kind1_id: params[:kind1_id]).pluck(:kind2, :id)
   # 初期値
    @kind2s.unshift(["選択してください。", ""])
  end

  def create
    @project = Entry.new(project_params)
    if @project.save
      redirect_to projects_path
    else
      render 'new'
    end
  end

  def update
    @project = Project.find(params[:id])
    if @project.update(project_params)
      redirect_to admin_list_path
    else
      render 'edit'
    end
  end

  def conversion
    require 'nkf'
    mecab = Natto::MeCab.new(node_format:'%m$$', unk_format:"%M$$", eos_format:"")
    @kana = NKF.nkf('-w -h2', params[:q][:name])
    @value = NKF.nkf('-w -m0Z1', params[:q][:name])
    @word = @value + ' ' + @kana
    @result = mecab.parse(@kana)
    @search = @result.split(/\$\$/)
    @search.map! do |del|
      del.gsub(/\s|　/,"")
    end
    @search.delete_if do |del|
      del =~ /^$/
    end
  end

  def detail
    mecab = Natto::MeCab.new(node_format:'%m,%f[6],%f[7],%f[8],%f[0]$$', unk_format:"%M,名詞$$", eos_format:"")
    word = @project.name + ',' + @project.about + ',' + @project.detail
    @result = mecab.parse(word)
    @result = @result.split(/\$\$/)
      @s = @result.select do |word|
      word =~ /,名詞|,動詞|,形容詞/
      end
      @s.map! do |str|
        str.split(/,/)
      end
      @s.each do |pop|
        pop.pop
      end
      @s.flatten!
      @search = @s.uniq
      @search.delete_if do |del|
        del =~ /^$|\.|\(|\)/
      end
  end

  def search
    @b = Search.search(:word_cont_any => @search)
    @before = @b.result
    @r = Hash.new(0)
    @before.each do |sum|
      @r[sum.project_id] += sum.tfidf
    end
    @sort = @r.sort{|(k1, v1), (k2, v2)| v2 <=> v1 }
    @sort.each do |del|
      del.pop
    end
    @sort.flatten!
  end

  def setup
  end

  def kind
    if params.include?('checked_param')
      if params[:checked_param].include?('全て')
        cookies.permanent[:kind] = nil
      else
        cookies.permanent[:kind] = params[:checked_param]
      end
    else
      cookies.permanent[:kind] = nil
    end
    redirect_to index_path
  end

  private
  def project_params
    params[:project].permit(:name, :kana, :about, :detail, :kind)
  end
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_detail.html.erb
<% if @lists.include?(@project.id.to_s) %>
  <%= button_to "お気に入り解除", {:action => "fav_remove_in_detail", :data => @project.id}, :remote => true, :class => "btn btn-danger" %>
<% else %>
  <%= button_to "お気に入り登録", {:action => "fav_detail", :data => @project.id}, :remote => true, :class => "btn btn-warning" %>
<% end %>
<i class='glyphicon glyphicon-star'></i>
<%= @favorite.count %>

app/views/projects/_form.html.erb
<%= form_for Project.new do |f| %>
<div class="form-group">
  <div class="input-group">
    <%= f.label '名前' %>
    <%= f.text_field :name, :placeholder => 'KeTchUp', :class => "form-control" %>
  </div>
  <div class="input-group">
    <%= f.label 'フリガナ' %>
    <%= f.text_field :kana, :placeholder => 'ケチャップ', :class => "form-control" %>
  </div>
  <div class="input-group">
    <%= f.label '概要' %>
    <%= f.text_field :about, :placeholder => 'おむらいすが製作した筑波大学用語辞典', :class => "form-control" %>
  </div>
  <div class="input-group">
    <%= f.label '詳細' %>
    <%= f.text_area :detail, :class => "form-control" %>
  </div>
  <div class="input-group">
    <%= f.label '大カテゴリー' %>
    <%= f.select :kind1, options_for_select(@kind1s.collect { |country| [country.kind1.titleize, country.id] }, 1), {}, { id: 'kind1s_select', :class => "form-control"} %>
  </div>
  <div class="input-group">
    <%= f.label '小カテゴリー' %>
    <%= f.text_field :kind2, :placeholder => 'イタリアン サークル等', :class => "form-control" %>
  </div>
  <div class="input-group">
    <%= f.label '同義語、類義語' %>
    <%= f.text_field :synonym, :placeholder => '辞書 辞典 事典 Webアプリケージョン', :class => "form-control" %>
  </div>
  <div class="input-group input_sub">
    <%= f.submit '登録', data: {:disable_with => '登録中', confirm: '登録希望をします。よろしいですか？'}, :class => 'btn btn-primary' %>
  </div>
</div>
<% end %>
<%= stylesheet_link_tag "form", :media => "all" %>

app/views/projects/_list.html.erb
<tr>
  <th><%= sort_link @q, :name, '用語名' %></th>
  <th><%= sort_link @q, :about, '概要' %></th>
  <th><%= sort_link @q, :kind1, '大カテゴリー' %></th>
  <th><%= sort_link @q, :kind2, '小カテゴリー' %></th>
  <th><%= sort_link @q, :count, 'お気に入り' %></th>
</tr>
<% @projects.each do |project| %>
<tr>
  <td><%= link_to project.name, project_path(project.id) %></td>
  <td><%= link_to project.about, project_path(project.id) %></td>
  <td><%= link_to project.kind1, project_path(project.id) %></td>
  <td><%= link_to project.kind2, project_path(project.id) %></td>
  <td>
    <% if @lists.include?(project.id.to_s) %>
      <%= button_to "お気に入り解除", {:action => "fav_remove", :data => {:id => project.id, :before => @projects.ids}}, :remote => true, :onclick => "disable()", :class => "btn btn-danger favorite_action" %>
    <% else %>
      <%= button_to "お気に入り登録", {:action => "fav", :data => {:id => project.id, :before => @projects.ids}}, :remote => true, :onclick => "disable()", :class => "btn btn-warning favorite_action" %>
    <% end %>
    <i class='glyphicon glyphicon-star'></i><span id="count"><%= project.count %></span>
  </td>
</tr>
<% end %>

app/views/projects/_project.html.erb
<div id="word" class="fadein">
  <%= link_to detail_path(@project.id) do %>
    <%= @project.id %>: <%= @project.name %>
  <% end %>
</div>

app/views/projects/_show.html.erb
<% if @lists.include?(@project.id.to_s) %>
  <%= button_to "お気に入り解除", {:action => "fav_remove", :data => {:id => @project.id, :before => nil}}, :remote => true, :onclick => "disable()", :class => "btn btn-danger favorite_action" %>
<% else %>
  <%= button_to "お気に入り登録", {:action => "fav", :data => {:id => @project.id, :before => nil}}, :remote => true, :onclick => "disable()", :class => "btn btn-warning favorite_action" %>
<% end %>
<i class='glyphicon glyphicon-star'></i>
<%= @project.count %>

app/views/projects/admin_detail.html.erb
<h1><%= @entry.id %>: <%= @entry.name %></h1>
<h2><%= @entry.group %></h2>
<p><%= @entry.about %></p>
<%= button_to "承認", {:action => "confirm", :data => {:id => @entry.id, :name => @entry.name, :group => @entry.group, :about => @entry.about, :kind => @entry.kind}}, :remote => false, :class => "btn btn-success" %>
<%= button_to "非承認", {:action => "reject", :data => @entry.id}, :remote => false, :class => "btn btn-danger" %>
<%= link_to 'トップ', projects_admin_path, :class => "btn btn-primary" %>

app/views/projects/index.html.erb
<header>
  <div class="title">
  <p>筑波大学用語辞典</p>
</div>
</header>
<%= link_to index_path, :class => 'top' do %>
  <%= image_tag 'image.png' , :width => '250', :height => '100'%>
<% end %>
<h1>検索結果一覧</h1>
<%= search_form_for @q do |f| %>
<div class="form-group">
  <div class="input-group">
    <%= f.text_field :name, :class => "form-control", :value => @value %>
    <span class="input-group-btn">
      <%= button_tag( class: "btn btn-primary", value: "search") do %>
        <%= content_tag :span, "検索", class: "glyphicon glyphicon-search" %>
      <% end %>
    </span>
  </div>
</div>
<% end %>
<%= link_to 'トップ', index_path, :class => "btn btn-success" %>
<% if @projects.size == 0 %>
  該当データがありません
<% else %>
  <%= page_entries_info @projects %>
<% end %>
<%= paginate @projects %>
<table id="list_fav" class="table table-striped">
  <tr>
    <th><%= sort_link @q, :name, '用語名' %></th>
    <th><%= sort_link @q, :about, '概要' %></th>
    <th><%= sort_link @q, :kind1, '大カテゴリー' %></th>
    <th><%= sort_link @q, :kind2, '小カテゴリー' %></th>
    <th><%= sort_link @q, :count, 'お気に入り' %></th>
  </tr>
  <% @projects.each do |project| %>
  <tr>
    <td><%= link_to project.name, project_path(project.id) %></td>
    <td><%= link_to project.about, project_path(project.id) %></td>
    <td><%= link_to project.kind1, project_path(project.id) %></td>
    <td><%= link_to project.kind2, project_path(project.id) %></td>
    <td>
      <% if @lists.include?(project.id.to_s) %>
        <%= button_to "お気に入り解除", {:action => "fav_remove", :data => {:id => project.id, :before => @projects.ids}}, :remote => true, :onclick => "disable()", :class => "btn btn-danger favorite_action" %>
      <% else %>
        <%= button_to "お気に入り登録", {:action => "fav", :data => {:id => project.id, :before => @projects.ids}}, :remote => true, :onclick => "disable(1)", :class => "btn btn-warning favorite_action" %>
      <% end %>
        <i class='glyphicon glyphicon-star'></i><span id="count"><%= project.count %></span>
    </td>
  </tr>
  <% end %>
</table>
<%= paginate @projects %>
<%= stylesheet_link_tag "list", :media => "all" %>
<%= javascript_include_tag "disable" %>

app/views/projects/index.js.erb
$('#list_fav').html('<%= j(render("list")) %>');

app/views/projects/kind.html.erb
<%= params[:checked_param] %>
<%= cookies[:kind] %>

app/views/projects/new.html.erb
<header>
  <div class="title">
  <p>筑波大学用語辞典</p>
</div>
</header>
<%= link_to index_path, :class => 'top' do %>
  <%= image_tag 'image.png' , :width => '250', :height => '100'%>
<% end %>

<h1>新規登録</h1>
<%= render 'form' %>

<%= stylesheet_link_tag "new", :media => "all" %>

app/views/projects/setup.html.erb
<header>
  <div class="title">
  <p>筑波大学用語辞典</p>
</div>
</header>
<%= link_to index_path, :class => 'top' do %>
  <%= image_tag 'image.png' , :width => '250', :height => '100'%>
<% end %>
<h1>設定</h1>
<div class="category_select">
<h2>トップページに表示するワードのカテゴリーを選択してください<br /><span>（複数回答可）</span></h2>
<% items = ['全て', 'イベント', 'ショッピングモール', 'スーパーマーケット', '飲食店', '図書館', '団体', '地名', 'その他'] %>
<%= form_tag('/kind') do %>
  <% items.each do |item| %>
  <label>
    <%= check_box_tag("checked_param[]", item ) %><%= item %>
  </label>
  <% end %>
  <%= submit_tag "設定", :class => "btn btn-primary" %>
<% end %>
</div>

<%= stylesheet_link_tag "setup", :media => "all" %>

app/views/projects/show.html.erb
<header>
  <div class="title">
  <p>筑波大学用語辞典</p>
</div>
</header>
<%= link_to index_path, :class => 'top' do %>
  <%= image_tag 'image.png' , :width => '250', :height => '100'%>
<% end %>
<div class="info_detail">
<h1><%= @project.name %></h1>
<p><%= simple_format(@project.detail.gsub(/\\n/, "\n")) %></p>
<p>大カテゴリー：<%= link_to @project.kind1, projects_path(kind: @project.kind1) %></p>
<p>小カテゴリー：<%= link_to @project.kind2,  projects_path(kind: @project.kind2) %></p>
</div>
<div id="fav_detail" class="center">
  <% if @lists.include?(@project.id.to_s) %>
    <%= button_to "お気に入り解除", {:action => "fav_remove", :data => {:id => @project.id, :before => nil}}, :remote => true, :onclick => "disable()", :class => "btn btn-danger favorite_action" %>
  <% else %>
    <%= button_to "お気に入り登録", {:action => "fav", :data => {:id => @project.id, :before => nil}}, :remote => true, :onclick => "disable()", :class => "btn btn-warning favorite_action" %>
  <% end %>
  <i class='glyphicon glyphicon-star'></i>
  <%= @project.count %>
</div>
<table id="list_fav" class="table table-striped">
  <tr>
    <th>似ているワード</th>
  </tr>
    <% @projects.each do |project| %>
        <tr>
          <td><%= link_to project.name, project_path(project.id) %></td>
        </tr>
  <% end %>
</table>

<%= link_to '前のページへ戻る', :back, :class => "btn btn-primary" %>
<%= link_to 'トップ', index_path, :class => "btn btn-success" %>

<%= stylesheet_link_tag "detail", :media=> "all" %>
<%= javascript_include_tag "disable" %>

app/views/projects/show.js.erb
$('#fav_detail').html('<%= j(render("show")) %>');