config/routes.rb
Rails.application.routes.draw do
  resources :projects

  get 'index' => 'index#index'

  get 'index/fav_list'

  get 'admin' => 'admin#index'

  get 'admin/index'

  get 'admin/projects' => 'admin#list', as: 'admin_list'

  get 'admin/projects/:id' => 'admin#detail', as: 'detail_admin'

  get 'admin/entries'

  get 'admin/reqest'

  get 'admin/entries/:id' => 'admin#approval', as: 'approval'

  get 'admin/projects/:id/edit' => 'admin#edit', as: 'edit'

  get 'admin/word_list' => 'admin#word_list'

  get 'fav' => 'projects#fav'

  get '/' => 'index#index'

  get 'setup' => 'projects#setup'

  post 'fav_remove' => 'projects#fav_remove'

  post 'fav_remove' => 'index#fav_remove'

  post 'fav' => 'projects#fav'

  post 'confirm' => 'admin#confirm'

  post 'reject' => 'admin#reject'

  post 'destroy' => 'admin#destroy'

  post 'make' => 'admin#make'

  post 'kind' => 'projects#kind'

end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <large>
    &nbsp;&nbsp;KeTchUp&nbsp;by&nbsp;おむらいす
  </large>
  <%= image_tag 'setting1.png' , :width => '13', :height => '13'%><%= link_to '設定', setup_path %>
</footer>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>KeTchUp</title>
  <%= include_gon %>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <%= favicon_link_tag %>
</head>
<body>

<%= yield %>
<%= render 'layouts/footer' %>
</body>
</html>